#!/usr/bin/env bash
# A Bash script that displays To infinity and beyond indefinitely until it receievd a SIGTERM, then displays "I am invincible!!!"
highlander() {
    echo "I am invincible!!!"
}

trap highlander  SIGTERM

while true; do
    echo "To infinity and beyond"
    sleep 2
done
