#!/usr/bin/env bash
# A Bash (init) script that manages manage_my_process

PIDF="/tmp/my_process.pid"
SCRIPTN="manage_my_process"

case "$1" in
    start)
        ./"$SCRIPTN" &
        echo $! > "$PIDF"
        echo "$SCRIPTN started"
        ;;
    stop)
        PID=$(cat "$PIDF")
        kill "$PID" 2>/dev/null
        rm -f "$PIDF"
        echo "$SCRIPTN stopped"
        ;;
    restart)
        PID=$(cat "$PIDF")
        kill "$PID" 2>/dev/null
        rm -f "$PIDF"
        ./"$SCRIPTN" &
        echo $! > "$PIDF"
        echo "$SCRIPTN restarted"
        ;;
    *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
        ;;
esac
