#!/usr/bin/env bash
# A Bash script that creates the file /tmp/myscript.pid containing its PID, displays To infinity and beyond indefinitely, displays I hate the kill command when receiving a SIGTERM signal, displays Y U no love me?! when receiving a SIGINT signal, and deletes the file /tmp/myscript.pid and terminates itself when receiving a SIGQUIT or SIGTERM signal
pgrep -f $0 > /tmp/myscript.pid

hate() {
    	echo "I hate the kill command"
	rm /tmp/myscript.pid
    	exit 0
}

why() {
	echo "Y U no love me?!"
	rm /tmp/myscript.pid
	exit 0
}

trap hate SIGTERM

trap why SIGINT

while true; do
    echo "To infinity and beyond"
    sleep 2
done
