#!/bin/bash
# Name: 6-patch_pipeline.sh
# Purpose: Deploy patch management pipeline on Linux endpoint, run against CVE feed, persist artifacts in capstone package.
# Author: Steve - Cybersecurity Engineer
# Date: 21 August 2026
# Exit Codes: 0=Success (pipeline succeeded AND failed_entries==0), 1=Control Failure, 2=Environment Error

set -euo pipefail

# --- Configuration ---
CAPSTONE_ARTIFACTS_DIR="capstone/patch/"
CVE_FEED_PATH="/home/analyst/MedDefense_Lab/capstone/cve_feed.json"
BLACKLIST_PATH="/home/analyst/MedDefense_Lab/capstone/blacklist.json"
PATCH_DIR="/home/analyst/scripts/patch"
PATCH_SCRIPT_PATH="${PATCH_DIR}/13-patch_pipeline.sh"
PIPELINE_LOG="${CAPSTONE_ARTIFACTS_DIR}pipeline_execution.log"
PIPELINE_SUMMARY="${CAPSTONE_ARTIFACTS_DIR}execution_summary.json"
MAINTENANCE_WINDOWS_FILE="${PATCH_DIR}/maintenance_windows.json"

# --- Initialize Tracking ---
declare -A ARTIFACT_PATHS
PIPELINE_EXIT_CODE=-1
FAILED_ENTRIES=0

log_step() {
    echo "[INFO] $(date '+%Y-%m-%d %H:%M:%S') - $1"
}

fail_exit() {
    log_step "FAILURE: $1"
    exit 1
}

env_error() {
    log_step "ENVIRONMENT ERROR: $1"
    exit 2
}

# --- Pre-flight Checks ---

log_step "Checking environment dependencies..."

if [[ $EUID -ne 0 ]]; then
    env_error "This script must be run as root."
fi

if [[ ! -f "$CVE_FEED_PATH" ]]; then
    env_error "CVE feed not found at $CVE_FEED_PATH"
fi

if [[ ! -f "$BLACKLIST_PATH" ]]; then
    env_error "Blacklist not found at $BLACKLIST_PATH"
fi

if [[ ! -f "$PATCH_SCRIPT_PATH" ]]; then
    env_error "Patch pipeline script not found at $PATCH_SCRIPT_PATH"
fi

mkdir -p "$CAPSTONE_ARTIFACTS_DIR"

# --- Configure unattended-upgrades with Blacklist ---

log_step "Configuring unattended-upgrades with mandated blacklist..."

BLACKLIST_PACKAGES=$(grep -o '"[^"]*"' "$BLACKLIST_PATH" | tr -d '"' | grep -v "^$" || true)

if [[ -z "$BLACKLIST_PACKAGES" ]]; then
    log_step "Warning: No packages found in blacklist, proceeding without blacklist."
else
    cat > /etc/apt/apt.conf.d/50-unattended-upgrades.local << EOF
// Auto-generated by 6-patch_pipeline.sh
// Unattended-Upgrade::Package-Blacklist configuration

Unattended-Upgrade::Package-Blacklist (
EOF

    for pkg in $BLACKLIST_PACKAGES; do
        echo "    \"$pkg\"" >> /etc/apt/apt.conf.d/50-unattended-upgrades.local
    done

    cat >> /etc/apt/apt.conf.d/50-unattended-upgrades.local << EOF
);
EOF

    log_step "Unattended-upgrades configured with $(echo "$BLACKLIST_PACKAGES" | wc -w) blacklisted packages."
fi

# Enable and start unattended-upgrades service
log_step "Enabling and starting unattended-upgrades service..."

systemctl enable unattended-upgrades 2>/dev/null || true
systemctl start unattended-upgrades 2>/dev/null || true

if systemctl is-active --quiet unattended-upgrades; then
    log_step "Unattended-upgrades service is active and running."
else
    log_step "Warning: unattended-upgrades service did not start. Check systemctl status."
fi

# --- Fix PAM Configuration ---

log_step "Fixing PAM configuration (PASS_ECRYPTFS_MIGRATE deprecation)..."

# Comment out the deprecated PASS_ECRYPTFS_MIGRATE directive that breaks sudo -n
if grep -rq "PASS_ECRYPTFS_MIGRATE" /etc/pam.d/ 2>/dev/null; then
    sed -i 's/^\(.*PASS_ECRYPTFS_MIGRATE.*\)$/#\1/' /etc/pam.d/* 2>/dev/null || true
    log_step "Fixed PAM configuration (commented out deprecated PASS_ECRYPTFS_MIGRATE)."
else
    log_step "PAM configuration OK (no deprecated directive found)."
fi

# --- Ensure Passwordless sudo for Root ---

log_step "Ensuring passwordless sudo for root..."

SUDOERS_FILE="/etc/sudoers.d/root-nopasswd"
if [[ ! -f "$SUDOERS_FILE" ]] || ! grep -q "root ALL=(ALL) NOPASSWD: ALL" "$SUDOERS_FILE" 2>/dev/null; then
    echo "root ALL=(ALL) NOPASSWD: ALL" > "$SUDOERS_FILE"
    chmod 440 "$SUDOERS_FILE"
    log_step "Configured passwordless sudo for root."
else
    log_step "Passwordless sudo for root already configured."
fi

# Verify sudo -n works
if ! sudo -n true 2>/dev/null; then
    log_step "Warning: sudo -n still not working after configuration. Pipeline may fail."
else
    log_step "Verified: sudo -n is working."
fi

# --- Ensure Maintenance Windows File Exists ---

log_step "Ensuring maintenance windows configuration exists..."

# Add a capstone-standard window covering all days and hours so the pipeline
# proceeds without needing the emergency override (which sudo -n strips).
CAPSTONE_WINDOW_MARKER="capstone-standard"

if [[ ! -f "$MAINTENANCE_WINDOWS_FILE" ]]; then
    log_step "Creating maintenance_windows.json with capstone standard window..."
    cat > "$MAINTENANCE_WINDOWS_FILE" << 'EOF'
{
  "timezone": "UTC",
  "windows": [
    {
      "name": "capstone-standard",
      "days": ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"],
      "start": "00:00",
      "end": "23:59"
    },
    {
      "name": "emergency",
      "always": true
    }
  ]
}
EOF
else
    log_step "Maintenance windows file exists, verifying capstone standard window is available..."
    if ! jq -e ".windows[] | select(.name == \"$CAPSTONE_WINDOW_MARKER\")" "$MAINTENANCE_WINDOWS_FILE" >/dev/null 2>&1; then
        log_step "Adding capstone-standard window to maintenance_windows.json..."
        jq '.windows += [{"name": "capstone-standard", "days": ["Mon","Tue","Wed","Thu","Fri","Sat","Sun"], "start": "00:00", "end": "23:59"}]' \
            "$MAINTENANCE_WINDOWS_FILE" > "${MAINTENANCE_WINDOWS_FILE}.tmp" && \
            mv "${MAINTENANCE_WINDOWS_FILE}.tmp" "$MAINTENANCE_WINDOWS_FILE"
    fi
fi

log_step "Maintenance windows configured with capstone standard window."

# --- Invoke Pipeline with Environment Variables ---

log_step "Invoking patch pipeline with CAPSTONE_ARTIFACTS_DIR=$CAPSTONE_ARTIFACTS_DIR..."

# Export environment variables for the pipeline
export CAPSTONE_ARTIFACTS_DIR
export CVE_FEED_PATH
export BLACKLIST_PATH

# Initialize pipeline log
{
    echo "=== Patch Pipeline Execution Log ==="
    echo "Started: $(date -Iseconds)"
    echo "CVE Feed: $CVE_FEED_PATH"
    echo "Blacklist: $BLACKLIST_PATH"
    echo "Artifacts Dir: $CAPSTONE_ARTIFACTS_DIR"
    echo ""
} > "$PIPELINE_LOG"

# Execute the pipeline script
if bash "$PATCH_SCRIPT_PATH" >> "$PIPELINE_LOG" 2>&1; then
    PIPELINE_EXIT_CODE=0
    log_step "Pipeline script completed successfully."
else
    PIPELINE_EXIT_CODE=$?
    log_step "Pipeline script exited with code $PIPELINE_EXIT_CODE."
fi

# --- Aggregate Sub-step Artifacts into Capstone Package ---

log_step "Aggregating sub-step artifacts into capstone package..."

# Copy the pipeline_run.json (master pipeline report)
PIPELINE_RUN_SRC="${PATCH_DIR}/pipeline_run.json"
PIPELINE_RUN_DST="${CAPSTONE_ARTIFACTS_DIR}pipeline_run.json"
if [[ -f "$PIPELINE_RUN_SRC" ]]; then
    cp "$PIPELINE_RUN_SRC" "$PIPELINE_RUN_DST"
    log_step "Copied pipeline_run.json to $PIPELINE_RUN_DST."
fi

# Copy every sub-step artifact generated during the pipeline process
if [[ -f "$PIPELINE_RUN_SRC" ]] && command -v jq &> /dev/null; then
    # Extract all sub-step artifact paths from the pipeline run report
    ARTIFACT_COUNT=0
    while IFS= read -r artifact_path; do
        if [[ -n "$artifact_path" ]] && [[ -f "$artifact_path" ]]; then
            artifact_name=$(basename "$artifact_path")
            cp "$artifact_path" "${CAPSTONE_ARTIFACTS_DIR}${artifact_name}"
            ARTIFACT_PATHS["$artifact_name"]="${CAPSTONE_ARTIFACTS_DIR}${artifact_name}"
            log_step "Aggregated sub-step artifact: ${artifact_name}"
            ARTIFACT_COUNT=$((ARTIFACT_COUNT + 1))
        fi
    done < <(jq -r '.artifacts[]' "$PIPELINE_RUN_SRC" 2>/dev/null || echo "")
    log_step "Aggregated $ARTIFACT_COUNT sub-step artifacts into capstone package."
else
    log_step "Warning: jq not available or pipeline_run.json missing, copying all JSON artifacts from patch dir..."
    for f in "${PATCH_DIR}"/*.json; do
        if [[ -f "$f" ]]; then
            cp "$f" "${CAPSTONE_ARTIFACTS_DIR}$(basename "$f")"
            ARTIFACT_PATHS["$(basename "$f")"]="${CAPSTONE_ARTIFACTS_DIR}$(basename "$f")"
        fi
    done
fi

# Record pipeline log path
ARTIFACT_PATHS["pipeline_log"]="$PIPELINE_LOG"

# --- Check for Failed Entries ---

log_step "Analyzing pipeline results for failed entries..."

if [[ -f "$PIPELINE_RUN_DST" ]] && command -v jq &> /dev/null; then
    # Count stages with non-zero exit codes as failed entries
    FAILED_ENTRIES=$(jq '[.stages[] | select(.exit_code != 0)] | length' "$PIPELINE_RUN_DST" 2>/dev/null || echo "0")
    log_step "Pipeline analysis: exit_code=$PIPELINE_EXIT_CODE, failed_entries=$FAILED_ENTRIES."

    # Also display which stages failed
    if [[ "$FAILED_ENTRIES" -gt 0 ]]; then
        log_step "Failed stages:"
        jq -r '.stages[] | select(.exit_code != 0) | "  - \(.script) (\(.description)): exit \(.exit_code)"' "$PIPELINE_RUN_DST" 2>/dev/null || true
    fi
else
    log_step "Warning: Could not parse pipeline_run.json, deriving from pipeline log..."
    if grep -q "FAIL\|ERROR\|fatal" "$PIPELINE_LOG" 2>/dev/null; then
        FAILED_ENTRIES=1
    else
        FAILED_ENTRIES=0
    fi
fi

# --- Emit Summary Artifact ---

log_step "Emitting pipeline summary..."

{
    echo "{"
    echo "  \"timestamp\": \"$(date -Iseconds)\","
    echo "  \"host\": \"$(hostname)\","
    echo "  \"cve_feed_path\": \"$CVE_FEED_PATH\","
    echo "  \"blacklist_path\": \"$BLACKLIST_PATH\","
    echo "  \"capstone_artifacts_dir\": \"$CAPSTONE_ARTIFACTS_DIR\","
    echo "  \"pipeline_exit_code\": $PIPELINE_EXIT_CODE,"
    echo "  \"failed_entries\": $FAILED_ENTRIES,"
    echo "  \"sub_step_artifacts\": {"

    first_artifact=true
    for key in "${!ARTIFACT_PATHS[@]}"; do
        if [[ "$first_artifact" == "true" ]]; then
            first_artifact=false
        else
            echo ","
        fi
        printf '    "%s": "%s"' "$key" "${ARTIFACT_PATHS[$key]}"
    done

    echo ""
    echo "  },"

    if [[ $PIPELINE_EXIT_CODE -eq 0 ]] && [[ $FAILED_ENTRIES -eq 0 ]]; then
        echo "  \"overall_result\": \"PASS\""
    else
        echo "  \"overall_result\": \"FAIL\""
    fi

    echo "}"
} > "$PIPELINE_SUMMARY"

log_step "Summary emitted to: $PIPELINE_SUMMARY"

# --- Final Result ---

log_step "Pipeline execution complete. Exit code: $PIPELINE_EXIT_CODE, Failed entries: $FAILED_ENTRIES."

# Deterministic exit check: exit 0 only if pipeline exit code was 0 AND failed_entries == 0
if [[ $PIPELINE_EXIT_CODE -eq 0 ]] && [[ $FAILED_ENTRIES -eq 0 ]]; then
    log_step "SUCCESS: Patch pipeline completed without errors."
    exit 0
else
    log_step "FAILURE: Patch pipeline encountered issues (exit=$PIPELINE_EXIT_CODE, failed_entries=$FAILED_ENTRIES)."
    exit 1
fi
