#!/bin/bash
#
# Name:        8-unattended_config.sh
# Purpose:     Configure unattended-upgrades with security-only origins, blacklist
#              critical packages, suppress automatic reboots, and verify via dry run
# Author:      Steve - Cybersecurity Engineer
# Date:        August 11, 2026
#

set -euo pipefail

readonly SCRIPT_NAME="$(basename "$0")"
readonly BASE_DIR="$(cd "$(dirname "$0")" && pwd)"

readonly CONFIG_50="/etc/apt/apt.conf.d/50unattended-upgrades"
readonly CONFIG_20="/etc/apt/apt.conf.d/20auto-upgrades"
readonly OUTPUT_FILE="${BASE_DIR}/unattended_config.json"

# Blacklisted package patterns — critical packages that must never auto-upgrade
readonly BLACKLIST=(
    "linux-image*"
    "linux-headers*"
    "mysql-server*"
    "apache2*"
    "libapache2-mod-php*"
)

log() {
    echo "[*] $*"
}

info() {
    echo "    $*"
}

warn() {
    echo "[!] $*" >&2
}

# ============================================
# STEP 1: Install unattended-upgrades if not present
# ============================================
ensure_installed() {
    if dpkg-query -W -f='${Status}' unattended-upgrades 2>/dev/null | grep -q "install ok installed"; then
        echo "already installed"
        return 0
    fi

    log "unattended-upgrades: installing..."
    DEBIAN_FRONTEND=noninteractive apt-get update -qq >/dev/null 2>&1
    DEBIAN_FRONTEND=noninteractive apt-get install -y unattended-upgrades >/dev/null 2>&1
    echo "installed"
}

# ============================================
# STEP 2: Write /etc/apt/apt.conf.d/50unattended-upgrades
# Idempotent: always overwrites the entire file
# ============================================
write_config_50() {
    # Build blacklist entries as quoted strings
    local blacklist_entries=""
    for pattern in "${BLACKLIST[@]}"; do
        blacklist_entries+="        \"${pattern}\";\n"
    done

    cat > "$CONFIG_50" <<EOF
// Auto-generated by 8-unattended_config.sh
// Configures unattended-upgrades for MedDefense billing-srv-01
// Only security origin is allowed; critical packages are blacklisted

Unattended-Upgrade::Allowed-Origins {
        "\${distro_id}:\${distro_codename}-security";
};

Unattended-Upgrade::Package-Blacklist {
$(echo -e "$blacklist_entries" | sed '/^$/d')
};

Unattended-Upgrade::Automatic-Reboot "false";
Unattended-Upgrade::Automatic-Reboot-Time "02:00";
Unattended-Upgrade::Remove-Unused-Kernel-Packages "false";
Unattended-Upgrade::Remove-New-Unused-Dependencies "false";
Unattended-Upgrade::Remove-Unused-Dependencies "false";

// Mail notifications disabled — no mail system in lab environment
Unattended-Upgrade::Mail "";
Unattended-Upgrade::Sender "";

Unattended-Upgrade::Automatic-Fix "true";
Unattended-Upgrade::MinimalSteps "true";
Unattended-Upgrade::InstallOnShutdown "false";
Unattended-Upgrade::OnlyOnACPower "true";
EOF

    chmod 644 "$CONFIG_50"
}

# ============================================
# STEP 3: Write /etc/apt/apt.conf.d/20auto-upgrades
# Idempotent: always overwrites the entire file
# ============================================
write_config_20() {
    cat > "$CONFIG_20" <<EOF
// Auto-generated by 8-unattended_config.sh
// Enables daily automated upgrade checks

APT::Periodic::Update-Package-Lists "1";
APT::Periodic::Download-Upgradeable-Packages "1";
APT::Periodic::AutocleanInterval "7";
APT::Periodic::Unattended-Upgrade "1";
EOF

    chmod 644 "$CONFIG_20"
}

# ============================================
# STEP 4: Enable and start timers
# ============================================
enable_timers() {
    local results='[]'

    for timer in apt-daily.timer apt-daily-upgrade.timer; do
        systemctl enable "$timer" >/dev/null 2>&1 || true
        systemctl start "$timer" >/dev/null 2>&1 || true

        local active_state
        active_state=$(systemctl show "$timer" --property=ActiveState --value 2>/dev/null || echo "unknown")

        local entry
        entry=$(jq -n --arg t "$timer" --arg s "$active_state" '{timer:$t, state:$s}')
        results=$(echo "$results" | jq ". + [$entry]")
    done

    echo "$results"
}

# ============================================
# STEP 5: Run dry run and parse output
# ============================================
run_dry_run() {
    log "Dry run..." >&2

    local dry_output
    dry_output=$(unattended-upgrades --dry-run --debug 2>&1 || true)

    local would_upgrade=0
    local skipped_blacklisted=0
    local skipped_held=0
    local blacklisted_names=""

    # Count packages that would be upgraded (Inst lines)
    would_upgrade=$(echo "$dry_output" | grep -cE '^Inst ' || true)
    [[ -z "$would_upgrade" ]] && would_upgrade=0

    # Count blacklisted packages that were skipped
    skipped_blacklisted=$(echo "$dry_output" | grep -ciE 'blacklist|skip.*black' || true)
    [[ -z "$skipped_blacklisted" ]] && skipped_blacklisted=0

    # Try to extract blacklisted package names
    blacklisted_names=$(echo "$dry_output" | \
        grep -iE 'blacklist|skip.*black' | \
        grep -oE '[a-zA-Z0-9][a-zA-Z0-9.+~-]*' | \
        sort -u | head -20 | tr '\n' ',' | sed 's/,$//' || echo "")

    # If the dry run output uses alternate language for blacklisted packages
    if [[ "$skipped_blacklisted" -eq 0 ]]; then
        skipped_blacklisted=$(echo "$dry_output" | \
            grep -ciE '(linux-image|linux-headers|mysql-server|apache2|libapache2-mod-php)' || true)
        [[ -z "$skipped_blacklisted" ]] && skipped_blacklisted=0

        blacklisted_names=$(echo "$dry_output" | \
            grep -iE '(linux-image|linux-headers|mysql-server|apache2|libapache2-mod-php)' | \
            grep -oE '[a-zA-Z0-9][a-zA-Z0-9.+~-]*' | \
            sort -u | head -20 | tr '\n' ',' | sed 's/,$//' || echo "")
    fi

    # Count held packages (dpkg hold)
    skipped_held=$(echo "$dry_output" | grep -ciE 'hold|held back' || true)
    [[ -z "$skipped_held" ]] && skipped_held=0

    # Print summary to console (stderr so it doesn't corrupt the JSON capture)
    printf "would upgrade:       %s\n" "$would_upgrade" >&2

    if [[ -n "$blacklisted_names" ]]; then
        printf "skipped (blacklist): %s (%s)\n" "$skipped_blacklisted" "$blacklisted_names" >&2
    else
        printf "skipped (blacklist): %s\n" "$skipped_blacklisted" >&2
    fi

    printf "skipped (held):      %s\n" "$skipped_held" >&2

    # Build summary JSON — only this goes to stdout
    jq -n \
        --argjson would_upgrade "$would_upgrade" \
        --argjson skipped_blacklisted "$skipped_blacklisted" \
        --argjson skipped_held "$skipped_held" \
        --arg blacklisted_names "$blacklisted_names" \
        '{
            would_upgrade: $would_upgrade,
            skipped_blacklisted: $skipped_blacklisted,
            skipped_held: $skipped_held,
            blacklisted_packages: $blacklisted_names
        }'
}

# ============================================
# MAIN
# ============================================
main() {
    log "Configuring unattended-upgrades for MedDefense..."

    # Step 1: Install if needed
    local install_status
    install_status=$(ensure_installed)
    log "unattended-upgrades: ${install_status}"

    # Step 2: Write 50unattended-upgrades
    printf "[*] Writing %s... " "$CONFIG_50"
    write_config_50
    echo "OK"

    # Step 3: Write 20auto-upgrades
    printf "[*] Writing %s... " "$CONFIG_20"
    write_config_20
    echo "OK"

    # Step 4: Enable timers
    printf "[*] Enabling timers... "
    local timer_state
    timer_state=$(enable_timers)
    echo "OK"

    # Step 5: Dry run
    local dry_run_summary
    dry_run_summary=$(run_dry_run)

    # Step 6: Emit JSON report
    local installed_bool=false
    if [[ "$install_status" == "already installed" ]] || [[ "$install_status" == "installed" ]]; then
        installed_bool=true
    fi

    # Build blacklist array for JSON
    local blacklist_json='[]'
    for pattern in "${BLACKLIST[@]}"; do
        local entry
        entry=$(jq -n --arg p "$pattern" '{pattern:$p}')
        blacklist_json=$(echo "$blacklist_json" | jq ". + [$entry]")
    done

    jq -n \
        --argjson installed "$installed_bool" \
        --arg config_50 "$CONFIG_50" \
        --arg config_20 "$CONFIG_20" \
        --argjson blacklist "$blacklist_json" \
        --argjson timers "$timer_state" \
        --argjson dry_run "$dry_run_summary" \
        '{
            installed: $installed,
            config_paths: [$config_50, $config_20],
            blacklist: $blacklist,
            timer_state: $timers,
            dry_run_summary: $dry_run
        }' > "$OUTPUT_FILE"

    log "Report saved to: $OUTPUT_FILE"
}

main "$@"
