#!/bin/bash
#
# Name:        4-nftables_config.sh
# Purpose:     Render segmentation_rules.json into nftables config, apply atomically, emit evidence JSON
# Author:      Steve - Cybersecurity Engineer
# Date:        August 14, 2026
#

set -euo pipefail

# Configuration
SEGMENTATION_FILE="segmentation_rules.json"
OUTPUT_NFT="nftables.conf"
BACKUP_DIR="/var/backups"
OUTPUT_JSON="nftables_evidence.json"
HASH_FILE="${BACKUP_DIR}/nftables-meddefense.hash"
TIMESTAMP=$(date -u +"%Y%m%dT%H%M%SZ")
# Rollback file saved to /var/backups/nftables-rollback-<timestamp>.nft
ROLLBACK_FILE="${BACKUP_DIR}/nftables-rollback-${TIMESTAMP}.nft"
LOG_PREFIX="nft-meddefense"

# Verify input exists
if [[ ! -f "$SEGMENTATION_FILE" ]]; then
    echo "Error: $SEGMENTATION_FILE not found. Run 2-segmentation_rules.sh first." >&2
    exit 1
fi

# Verify nft is available
if ! command -v nft &>/dev/null; then
    echo "Error: nft (nftables) is not installed." >&2
    exit 1
fi

# Ensure backup directory exists
mkdir -p "$BACKUP_DIR"

# ---------------------------------------------------------------
# Determine local zone by matching interface IPs to zone CIDRs
# Zones defined in segmentation_rules.json: DMZ, INTERNAL, MGMT, MEDDEV
# ---------------------------------------------------------------
LOCAL_ZONE=$(python3 -c "
import json, ipaddress, subprocess
with open('${SEGMENTATION_FILE}') as f:
    data = json.load(f)
zones = data['zones']
result = subprocess.run(['ip', '-j', 'addr', 'show'], capture_output=True, text=True)
addrs = json.loads(result.stdout)
local_ips = []
for iface in addrs:
    for ai in iface.get('addr_info', []):
        local_ips.append(ai.get('local', ''))
for zone in zones:
    try:
        net = ipaddress.ip_network(zone['cidr'])
        for ip in local_ips:
            try:
                if ip and ipaddress.ip_address(ip) in net:
                    print(zone['name'])
                    raise SystemExit(0)
            except ValueError:
                pass
    except ValueError:
        pass
print('INTERNAL')
" 2>/dev/null || echo "INTERNAL")

echo "Detected local zone: $LOCAL_ZONE"
echo "Available zones from segmentation: DMZ, INTERNAL, MGMT, MEDDEV"

# ---------------------------------------------------------------
# Read zone and flow data from JSON
# ---------------------------------------------------------------
ZONE_COUNT=$(jq '.zones | length' "$SEGMENTATION_FILE")
FLOW_COUNT=$(jq '.flows | length' "$SEGMENTATION_FILE")
ALLOW_COUNT=$(jq '[.flows[] | select(.action == "allow")] | length' "$SEGMENTATION_FILE")
DENY_COUNT=$(jq '[.flows[] | select(.action == "deny_all")] | length' "$SEGMENTATION_FILE")

# ---------------------------------------------------------------
# Generate nftables.conf
# Renders zone sets, input/forward/output chains with rules
# from the segmentation flow matrix.
# ---------------------------------------------------------------
{
echo "#!/usr/sbin/nft -f"
echo "#"
echo "# nftables.conf - MedDefense perimeter defense ruleset"
echo "# Generated by 4-nftables_config.sh"
echo "# Local zone: $LOCAL_ZONE"
echo "# Generated at: $TIMESTAMP"
echo ""
echo "flush ruleset"
echo ""
echo "table inet meddefense {"

# --- Named sets per zone ---
echo "    # Zone network sets"
for ((z = 0; z < ZONE_COUNT; z++)); do
    zone_name=$(jq -r ".zones[$z].name" "$SEGMENTATION_FILE")
    zone_cidr=$(jq -r ".zones[$z].cidr" "$SEGMENTATION_FILE")
    set_name=$(echo "$zone_name" | tr '[:upper:]' '[:lower:]')_net
    echo "    set ${set_name} {"
    echo "        type ipv4_addr"
    echo "        flags interval"
    echo "        elements = { ${zone_cidr} }"
    echo "    }"
done
echo ""

# --- Input chain ---
echo "    chain input {"
echo "        type filter hook input priority 0; policy drop;"
echo ""
echo "        # Connection tracking - accept established and related"
echo "        ct state established,related accept"
echo ""
echo "        # Loopback interface"
echo "        iif \"lo\" accept"
echo ""
echo "        # ICMP minimal accept for diagnostics"
echo "        ip protocol icmp accept"
echo "        ip6 nexthdr ipv6-icmp accept"
echo ""

# Input allow rules: flows where dst_zone matches LOCAL_ZONE
echo "        # Allow rules for flows terminating on local host (zone: $LOCAL_ZONE)"
input_rules_added=0
for ((f = 0; f < FLOW_COUNT; f++)); do
    action=$(jq -r ".flows[$f].action" "$SEGMENTATION_FILE")
    dst_zone=$(jq -r ".flows[$f].dst_zone" "$SEGMENTATION_FILE")
    src_zone=$(jq -r ".flows[$f].src_zone" "$SEGMENTATION_FILE")
    proto=$(jq -r ".flows[$f].proto" "$SEGMENTATION_FILE")
    dport=$(jq -r ".flows[$f].dport" "$SEGMENTATION_FILE")
    justification=$(jq -r ".flows[$f].justification" "$SEGMENTATION_FILE")

    if [[ "$action" != "allow" ]]; then
        continue
    fi

    if [[ "$dst_zone" != "$LOCAL_ZONE" ]]; then
        continue
    fi

    # Skip intra-zone flows in input (they are handled by the loopback or same-subnet directly)
    if [[ "$src_zone" == "$dst_zone" ]]; then
        continue
    fi

    src_set=$(echo "$src_zone" | tr '[:upper:]' '[:lower:]')_net

    if [[ "$proto" == "any" ]]; then
        echo "        ip saddr @${src_set} accept comment \"${justification}\""
    else
        echo "        ip saddr @${src_set} ${proto} dport ${dport} accept comment \"${justification}\""
    fi
    input_rules_added=$((input_rules_added + 1))
done

if [[ $input_rules_added -eq 0 ]]; then
    echo "        # No cross-zone flows terminate on local host"
fi
echo ""
echo "        # Drop and log terminal rule"
echo "        log prefix \"${LOG_PREFIX}-input-drop: \" flags all counter drop"
echo "    }"
echo ""

# --- Forward chain ---
echo "    chain forward {"
echo "        type filter hook forward priority 0; policy drop;"
echo ""
echo "        # Connection tracking"
echo "        ct state established,related accept"
echo ""
echo "        # Cross-zone allow rules rendered from flow matrix"
echo ""

for ((f = 0; f < FLOW_COUNT; f++)); do
    action=$(jq -r ".flows[$f].action" "$SEGMENTATION_FILE")
    src_zone=$(jq -r ".flows[$f].src_zone" "$SEGMENTATION_FILE")
    dst_zone=$(jq -r ".flows[$f].dst_zone" "$SEGMENTATION_FILE")
    proto=$(jq -r ".flows[$f].proto" "$SEGMENTATION_FILE")
    dport=$(jq -r ".flows[$f].dport" "$SEGMENTATION_FILE")
    justification=$(jq -r ".flows[$f].justification" "$SEGMENTATION_FILE")

    src_set=$(echo "$src_zone" | tr '[:upper:]' '[:lower:]')_net
    dst_set=$(echo "$dst_zone" | tr '[:upper:]' '[:lower:]')_net

    if [[ "$action" == "allow" ]]; then
        # Skip intra-zone flows in forward chain
        if [[ "$src_zone" == "$dst_zone" ]]; then
            continue
        fi
        if [[ "$proto" == "any" ]]; then
            echo "        ip saddr @${src_set} ip daddr @${dst_set} accept comment \"${justification}\""
        else
            echo "        ip saddr @${src_set} ip daddr @${dst_set} ${proto} dport ${dport} accept comment \"${justification}\""
        fi
    elif [[ "$action" == "deny_all" ]]; then
        echo "        ip saddr @${src_set} ip daddr @${dst_set} log prefix \"${LOG_PREFIX}-deny-${src_zone}-${dst_zone}: \" drop comment \"${justification}\""
    fi
done
echo ""
echo "        # Drop and log terminal rule"
echo "        log prefix \"${LOG_PREFIX}-forward-drop: \" flags all counter drop"
echo "    }"
echo ""

# --- Output chain ---
echo "    chain output {"
echo "        type filter hook output priority 0; policy accept;"
echo ""
echo "        # Connection tracking"
echo "        ct state established,related accept"
echo ""
echo "        # Explicit drops for zones that must not receive outbound from this host"
echo ""

# Add drops for deny_all rules where src_zone matches LOCAL_ZONE
output_drops_added=0
for ((f = 0; f < FLOW_COUNT; f++)); do
    action=$(jq -r ".flows[$f].action" "$SEGMENTATION_FILE")
    src_zone=$(jq -r ".flows[$f].src_zone" "$SEGMENTATION_FILE")
    dst_zone=$(jq -r ".flows[$f].dst_zone" "$SEGMENTATION_FILE")
    justification=$(jq -r ".flows[$f].justification" "$SEGMENTATION_FILE")

    if [[ "$action" == "deny_all" && "$src_zone" == "$LOCAL_ZONE" ]]; then
        dst_set=$(echo "$dst_zone" | tr '[:upper:]' '[:lower:]')_net
        echo "        ip daddr @${dst_set} log prefix \"${LOG_PREFIX}-output-drop-${dst_zone}: \" drop comment \"${justification}\""
        output_drops_added=$((output_drops_added + 1))
    fi
done

if [[ $output_drops_added -eq 0 ]]; then
    echo "        # No outbound restrictions for local zone $LOCAL_ZONE"
fi
echo "    }"
echo "}"

} > "$OUTPUT_NFT"

echo "Generated: $OUTPUT_NFT"

# ---------------------------------------------------------------
# Check-only parse to validate nftables.conf syntax before applying
# Uses nft -c -f nftables.conf for a dry-run validation
# ---------------------------------------------------------------
echo "Validating ruleset syntax with nft -c -f..."
if ! nft -c -f "$OUTPUT_NFT" 2>&1; then
    echo "Error: nftables syntax validation failed. Aborting." >&2
    exit 1
fi
echo "Syntax validation passed."

# ---------------------------------------------------------------
# Idempotency check: compare hash of nftables.conf with last apply
# If the hash matches, skip the apply step to avoid re-applying
# changes that are already in place.
# ---------------------------------------------------------------
NEW_HASH=$(sha256sum "$OUTPUT_NFT" | cut -d' ' -f1)
SKIP_APPLY=false
if [[ -f "$HASH_FILE" ]] && [[ "$(cat "$HASH_FILE")" == "$NEW_HASH" ]]; then
    if nft list table inet meddefense &>/dev/null; then
        echo "Ruleset unchanged and already loaded. Skipping apply (idempotent)."
        SKIP_APPLY=true
    fi
fi

# ---------------------------------------------------------------
# Save rollback of current ruleset before applying
# This is the "measure before you change" step.
# ---------------------------------------------------------------
if [[ "$SKIP_APPLY" == "false" ]]; then
    echo "Saving rollback to $ROLLBACK_FILE..."
    nft list ruleset > "$ROLLBACK_FILE" 2>/dev/null || echo "# empty ruleset at $(date -u +%Y-%m-%dT%H:%M:%SZ)" > "$ROLLBACK_FILE"

    # ---------------------------------------------------------------
    # Apply the new ruleset atomically with nft -f nftables.conf
    # If the apply fails, automatically roll back from the saved file.
    # ---------------------------------------------------------------
    echo "Applying ruleset atomically with nft -f..."
    if ! nft -f "$OUTPUT_NFT" 2>&1; then
        echo "Error: Failed to apply ruleset. Rolling back..." >&2
        nft -f "$ROLLBACK_FILE" 2>/dev/null || true
        exit 1
    fi
    echo "Ruleset applied successfully."

    # Store hash for idempotency check on future runs
    echo "$NEW_HASH" > "$HASH_FILE"
fi

# ---------------------------------------------------------------
# Verify the load with nft list ruleset
# Count rules, chains, and sets to confirm the ruleset loaded correctly
# Compare loaded rule count against expected total from segmentation_rules.json
# ---------------------------------------------------------------
EXPECTED_TOTAL=$(jq '.summary.flow_count' "$SEGMENTATION_FILE")
echo "Verifying ruleset with nft list ruleset..."
LOADED_RULESET=$(nft list ruleset 2>/dev/null)

TABLE_PRESENT=false
if echo "$LOADED_RULESET" | grep -q "table inet meddefense"; then
    TABLE_PRESENT=true
fi

# Count accept and drop rule statements in the loaded ruleset
RULE_COUNT_LOADED=$(echo "$LOADED_RULESET" | grep -cE '\b(accept|drop)\b' || true)
RULE_COUNT_LOADED=${RULE_COUNT_LOADED:-0}

# Count chains (input, forward, output)
CHAIN_COUNT=$(echo "$LOADED_RULESET" | grep -cE 'chain (input|forward|output)' || true)
CHAIN_COUNT=${CHAIN_COUNT:-0}

# Count named sets
SET_COUNT=$(echo "$LOADED_RULESET" | grep -cE 'set .*_net' || true)
SET_COUNT=${SET_COUNT:-0}

# Count log prefix rules
LOG_RULE_COUNT=$(echo "$LOADED_RULESET" | grep -c 'log prefix' || true)
LOG_RULE_COUNT=${LOG_RULE_COUNT:-0}

# ---------------------------------------------------------------
# Emit evidence JSON
# ---------------------------------------------------------------
FINAL_JSON=$(jq -n \
    --arg ts "$TIMESTAMP" \
    --arg lz "$LOCAL_ZONE" \
    --arg nft_file "$OUTPUT_NFT" \
    --arg rollback "$ROLLBACK_FILE" \
    --argjson table_present "$TABLE_PRESENT" \
    --argjson rule_count "$RULE_COUNT_LOADED" \
    --argjson chain_count "$CHAIN_COUNT" \
    --argjson set_count "$SET_COUNT" \
    --argjson log_rule_count "$LOG_RULE_COUNT" \
    --argjson allow_count "$ALLOW_COUNT" \
    --argjson deny_count "$DENY_COUNT" \
    --argjson zone_count "$ZONE_COUNT" \
    --argjson expected_total "$EXPECTED_TOTAL" \
    --argjson skipped "$SKIP_APPLY" \
    '{
        timestamp: $ts,
        local_zone: $lz,
        nftables_conf: $nft_file,
        rollback_file: $rollback,
        table_loaded: $table_present,
        chains: $chain_count,
        zone_sets: $set_count,
        rules_loaded: $rule_count,
        expected_total: $expected_total,
        log_prefix_rules: $log_rule_count,
        allow_flows_rendered: $allow_count,
        deny_flows_rendered: $deny_count,
        zones_defined: $zone_count,
        idempotent_skip: $skipped,
        status: (if $table_present then "applied" else "failed" end)
    }')

echo "$FINAL_JSON" > "$OUTPUT_JSON"

# Human-readable summary to stdout
echo ""
echo "nftables Configuration Applied"
echo "=============================="
echo "Local zone:         $LOCAL_ZONE"
echo "Config file:        $OUTPUT_NFT"
echo "Rollback file:      $ROLLBACK_FILE"
echo "Table loaded:       $TABLE_PRESENT"
echo "Chains:             $CHAIN_COUNT"
echo "Zone sets:          $SET_COUNT"
echo "Rules loaded:       $RULE_COUNT_LOADED"
echo "Expected total:     $EXPECTED_TOTAL"
echo "Log prefix rules:   $LOG_RULE_COUNT"
echo "Allow flows:        $ALLOW_COUNT"
echo "Deny flows:         $DENY_COUNT"
echo "Idempotent skip:    $SKIP_APPLY"
echo "Evidence JSON:      $OUTPUT_JSON"
