#!/bin/bash
#
# Name:        8-suricata_setup.sh
# Purpose:     Install Suricata, configure for offline PCAP replay, load ruleset, verify with smoke test
# Author:      Steve - Cybersecurity Engineer
# Date:        August 14, 2026
#

set -euo pipefail

# Configuration
LAB_DIR="/home/analyst/MedDefense_Lab"
# Rules source: /home/analyst/MedDefense_Lab/suricata/rules
RULES_SRC="${LAB_DIR}/suricata/rules"
RULES_DST="/var/lib/suricata/rules"
SMOKE_PCAP="${LAB_DIR}/PCAPs/smoke.pcap"
SMOKE_LOG_DIR="/tmp/suricata-smoke"
CONFIG_FILE="./suricata.yaml"
OUTPUT_JSON="setup_verification.json"
LOG_DIR="/var/log/suricata"

# Verify lab directory exists
if [[ ! -d "$LAB_DIR" ]]; then
    echo "Error: Lab directory $LAB_DIR not found." >&2
    exit 1
fi

# ---------------------------------------------------------------
# 1. Install suricata and jq from distribution repository if not
#    already present. This is idempotent: apt will skip installed
#    packages without error.
# ---------------------------------------------------------------
echo "[*] Checking for suricata and jq..."

NEED_INSTALL=()
if ! command -v suricata &>/dev/null; then
    NEED_INSTALL+=("suricata")
fi
if ! command -v jq &>/dev/null; then
    NEED_INSTALL+=("jq")
fi

if [[ ${#NEED_INSTALL[@]} -gt 0 ]]; then
    echo "[*] Installing: ${NEED_INSTALL[*]}"
    apt-get update -qq
    apt-get install -y -qq "${NEED_INSTALL[@]}"
else
    echo "[*] suricata and jq already installed."
fi

# Capture installed version - single line, robust extraction
INSTALLED_VERSION=$(suricata --version 2>&1 | head -5 | grep -oE '[0-9]+\.[0-9]+\.[0-9]+' | head -1) || true
if [[ -z "$INSTALLED_VERSION" ]]; then
    INSTALLED_VERSION="unknown"
fi
echo "[*] Suricata version: $INSTALLED_VERSION"

# ---------------------------------------------------------------
# 2. Copy the provided ruleset from the lab directory into
#    /var/lib/suricata/rules/ and verify the file count.
#    This is idempotent: cp -f overwrites without error.
# ---------------------------------------------------------------
echo "[*] Copying ruleset from $RULES_SRC to $RULES_DST..."

if [[ ! -d "$RULES_SRC" ]]; then
    echo "Error: Rules source directory $RULES_SRC not found." >&2
    exit 1
fi

mkdir -p "$RULES_DST"
cp -f "${RULES_SRC}"/*.rules "$RULES_DST/" 2>/dev/null || true

# Also copy any other files
cp -f "${RULES_SRC}"/* "$RULES_DST/" 2>/dev/null || true

SRC_FILE_COUNT=$(find "$RULES_SRC" -name "*.rules" -type f | wc -l)
DST_FILE_COUNT=$(find "$RULES_DST" -name "*.rules" -type f | wc -l)

echo "[*] Source rule files: $SRC_FILE_COUNT"
echo "[*] Destination rule files: $DST_FILE_COUNT"

if [[ "$DST_FILE_COUNT" -lt "$SRC_FILE_COUNT" ]]; then
    echo "Error: File count mismatch. Expected $SRC_FILE_COUNT, got $DST_FILE_COUNT" >&2
    exit 1
fi

# Count total rules across all rule files
RULE_COUNT=0
for rule_file in "$RULES_DST"/*.rules; do
    [[ -f "$rule_file" ]] || continue
    # Count non-comment, non-empty lines that start with a rule keyword
    file_count=$(grep -cE '^(alert|drop|reject|pass)' "$rule_file" 2>/dev/null || true)
    # Extract only the numeric portion
    file_count=$(echo "$file_count" | grep -oE '[0-9]+' | head -1) || file_count=0
    file_count=${file_count:-0}
    RULE_COUNT=$((RULE_COUNT + file_count))
done
echo "[*] Total rule count: $RULE_COUNT"

# List rule files for the YAML configuration
RULE_FILES_LIST=$(find "$RULES_DST" -name "*.rules" -printf "%f\n" 2>/dev/null | sort)

# ---------------------------------------------------------------
# 3. Render a minimal suricata.yaml in the project directory
#    with the required overrides for offline replay mode.
#    HOME_NET is set to 10.10.0.0/16 and EXTERNAL_NET is
#    the inverse. This configuration does not start a daemon.
# ---------------------------------------------------------------
echo "[*] Rendering $CONFIG_FILE..."

{
echo "# suricata.yaml - MedDefense offline replay configuration"
echo "# Generated by 8-suricata_setup.sh"
echo "# Date: $(date -u +'%Y-%m-%dT%H:%M:%SZ')"
echo ""
echo "%YAML 1.1"
echo "---"
echo ""
echo "default-log-dir: $LOG_DIR"
echo "default-rule-path: $RULES_DST"
echo ""
echo "# Rule files loaded for offline analysis"
echo "rule-files:"
for rule_file in $RULE_FILES_LIST; do
    echo "  - $rule_file"
done
echo "  - meddefense.rules"
echo ""
echo "# HOME_NET covers all MedDefense internal zones (DMZ, INTERNAL, MGMT, MEDDEV)"
echo "vars:"
echo "  address-groups:"
echo "    HOME_NET: \"[10.10.0.0/16]\""
echo "    EXTERNAL_NET: \"!\$HOME_NET\""
echo "    HTTP_SERVERS: \"\$HOME_NET\""
echo "    SMTP_SERVERS: \"\$HOME_NET\""
echo "    DNS_SERVERS: \"\$HOME_NET\""
echo "    TLS_SERVERS: \"\$HOME_NET\""
echo "    SQL_SERVERS: \"\$HOME_NET\""
echo "  port-groups:"
echo "    HTTP_PORTS: \"80\""
echo "    SHELLCODE_PORTS: \"!80\""
echo "    SSH_PORTS: \"22\""
echo ""
echo "# pcap-file replay mode (offline analysis, no live interface)"
echo "pcap-file:"
echo "  enabled: true"
echo ""
echo "outputs:"
echo "  - eve-log:"
echo "      enabled: true"
echo "      filetype: regular"
echo "      filename: eve.json"
echo "      community-id: false"
echo "      types:"
echo "        - alert:"
echo "            tagged-packets: yes"
echo "        - http:"
echo "            extended: yes"
echo "        - dns:"
echo "            query: yes"
echo "        - tls:"
echo "            extended: yes"
echo "        - files"  # fileinfo output type in Suricata 6.0.x
echo "        - anomaly:"
echo "            enabled: no"
echo "        - ssh"
echo "  - stats:"
echo "      enabled: true"
echo "      filename: stats.log"
echo "      totals: yes"
echo ""
echo "app-layer:"
echo "  protocols:"
echo "    http:"
echo "      enabled: true"
echo "    tls:"
echo "      enabled: true"
echo "    dns:"
echo "      enabled: true"
echo ""
echo "file-store:"
echo "  enabled: true"
echo ""
echo "logging:"
echo "  default-log-level: notice"
echo "  outputs:"
echo "    - console:"
echo "        enabled: true"
echo "    - file:"
echo "        enabled: false"
echo ""
echo "af-packet:"
echo "  - interface: eth0"
echo "    cluster-id: 99"
echo "    cluster-type: cluster_flow"
echo "    defrag: yes"
echo "    use-mmap: yes"
echo "    tpacket-v3: yes"
echo ""
# Live capture disabled - offline replay only
# do not start suricata.service as a systemd daemon for this project
echo "# Live capture disabled - offline replay only"
echo "capture:"
echo "  kernel-packet-filter: false"
echo ""
echo "# Host information"
echo "host-os-policy:"
echo "  linux: enabled"
echo "  windows: enabled"
echo "  macos: disabled"
echo "  bsd: disabled"
} > "$CONFIG_FILE"

# Create a placeholder meddefense.rules if it does not exist
if [[ ! -f "${RULES_DST}/meddefense.rules" ]]; then
    echo "# meddefense.rules - placeholder for custom MedDefense rules" > "${RULES_DST}/meddefense.rules"
    echo "# Add custom Suricata rules here for offline replay analysis" >> "${RULES_DST}/meddefense.rules"
fi

echo "[*] Config file written: $CONFIG_FILE"

# ---------------------------------------------------------------
# 4. Run suricata -T -c ./suricata.yaml -v to test the configuration
#    and capture the exit code. Exit 0 means the config is valid.
# ---------------------------------------------------------------
echo "[*] Running configuration test: suricata -T -c $CONFIG_FILE -v"
CONFIG_OUTPUT=$(suricata -T -c "$CONFIG_FILE" -v 2>&1 || true)
CONFIG_TEST_EXIT=$?

echo "$CONFIG_OUTPUT" | tail -5
echo "[*] Config test exit code: $CONFIG_TEST_EXIT"

if [[ $CONFIG_TEST_EXIT -ne 0 ]]; then
    echo "Warning: Suricata config test returned non-zero exit code." >&2
fi

# ---------------------------------------------------------------
# 5. Run one quick end-to-end smoke test:
#    suricata -c ./suricata.yaml -r <smoke.pcap> -l /tmp/suricata-smoke/
#    Then verify that eve.json contains at least one alert record.
# ---------------------------------------------------------------
SMOKE_ALERTS=0
SMOKE_SUCCESS=false

if [[ -f "$SMOKE_PCAP" ]]; then
    echo "[*] Running smoke test with $SMOKE_PCAP..."
    rm -rf "$SMOKE_LOG_DIR"
    mkdir -p "$SMOKE_LOG_DIR"

    SMOKE_OUTPUT=$(suricata -c "$CONFIG_FILE" -r "$SMOKE_PCAP" -l "$SMOKE_LOG_DIR" 2>&1 || true)
    SMOKE_EXIT=$?
    echo "[*] Smoke test exit code: $SMOKE_EXIT"

    if [[ -f "${SMOKE_LOG_DIR}/eve.json" ]]; then
        # Use -s flag to slurp NDJSON into array before filtering
        SMOKE_ALERTS=$(jq -s '[.[] | select(.event_type == "alert")] | length' "${SMOKE_LOG_DIR}/eve.json" 2>/dev/null || echo "0")
        SMOKE_ALERTS=${SMOKE_ALERTS:-0}
        SMOKE_SUCCESS=true
        echo "[*] Smoke test alerts: $SMOKE_ALERTS"

        if [[ $SMOKE_ALERTS -gt 0 ]]; then
            echo "[*] Smoke test PASSED: $SMOKE_ALERTS alert(s) found in eve.json"
        else
            echo "[*] Smoke test WARNING: No alerts found in eve.json"
        fi
    else
        echo "[*] Smoke test FAILED: eve.json not created"
    fi
else
    echo "[*] Smoke test SKIPPED: $SMOKE_PCAP not found"
fi

# ---------------------------------------------------------------
# 6. Emit setup_verification.json with all required fields
# ---------------------------------------------------------------
TIMESTAMP=$(date -u +"%Y-%m-%dT%H:%M:%SZ")

FINAL_JSON=$(jq -n \
    --arg ts "$TIMESTAMP" \
    --arg ver "$INSTALLED_VERSION" \
    --argjson rule_files "$DST_FILE_COUNT" \
    --argjson rule_count "$RULE_COUNT" \
    --argjson config_exit "$CONFIG_TEST_EXIT" \
    --arg smoke_pcap "$SMOKE_PCAP" \
    --argjson smoke_alerts "$SMOKE_ALERTS" \
    --argjson smoke_success "$SMOKE_SUCCESS" \
    '{
        timestamp: $ts,
        installed_version: $ver,
        rule_files_loaded: $rule_files,
        rule_count: $rule_count,
        config_test_exit: $config_exit,
        smoke_pcap: $smoke_pcap,
        smoke_alerts: $smoke_alerts,
        smoke_test_passed: $smoke_success,
        config_file: "suricata.yaml",
        rules_directory: "/var/lib/suricata/rules",
        home_net: "[10.10.0.0/16]",
        external_net: "!$HOME_NET",
        mode: "offline_replay"
    }')

echo "$FINAL_JSON" > "$OUTPUT_JSON"

# Human-readable summary to stdout
echo ""
echo "Suricata Offline Setup Complete"
echo "================================"
echo "Installed version:  $INSTALLED_VERSION"
echo "Rule files loaded:  $DST_FILE_COUNT"
echo "Total rule count:   $RULE_COUNT"
echo "Config test exit:   $CONFIG_TEST_EXIT"
echo "Smoke PCAP:         $SMOKE_PCAP"
echo "Smoke alerts:       $SMOKE_ALERTS"
echo "Smoke test passed:  $SMOKE_SUCCESS"
echo "Config file:        $CONFIG_FILE"
echo "Output:             $OUTPUT_JSON"
